<?php

namespace Database\Seeders;

use App\Models\Cliente;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $clientes = [
            [
                'nombre' => 'Juan',
                'apellido' => 'Pérez',
                'identificacion' => '0102030401',
                'telefono' => '0987654321',
                'email' => 'juan.perez@example.com',
                'limite_credito' => 500.00,
            ],
            [
                'nombre' => 'María',
                'apellido' => 'González',
                'identificacion' => '0102030402',
                'telefono' => '0987654322',
                'email' => 'maria.gonzalez@example.com',
                'limite_credito' => 800.00,
            ],
            [
                'nombre' => 'Carlos',
                'apellido' => 'Rodríguez',
                'identificacion' => '0102030403',
                'telefono' => '0987654323',
                'email' => 'carlos.rodriguez@example.com',
                'limite_credito' => 1000.00,
            ],
            [
                'nombre' => 'Ana',
                'apellido' => 'Martínez',
                'identificacion' => '0102030404',
                'telefono' => '0987654324',
                'email' => 'ana.martinez@example.com',
                'limite_credito' => 600.00,
            ],
            [
                'nombre' => 'Luis',
                'apellido' => 'Vargas',
                'identificacion' => '0102030405',
                'telefono' => '0987654325',
                'email' => 'luis.vargas@example.com',
                'limite_credito' => 750.00,
            ],
            [
                'nombre' => 'Sofía',
                'apellido' => 'Ramírez',
                'identificacion' => '0102030406',
                'telefono' => '0987654326',
                'email' => 'sofia.ramirez@example.com',
                'limite_credito' => 900.00,
            ],
            [
                'nombre' => 'Pedro',
                'apellido' => 'Mendoza',
                'identificacion' => '0102030407',
                'telefono' => '0987654327',
                'email' => 'pedro.mendoza@example.com',
                'limite_credito' => 450.00,
            ],
            [
                'nombre' => 'Daniela',
                'apellido' => 'Torres',
                'identificacion' => '0102030408',
                'telefono' => '0987654328',
                'email' => 'daniela.torres@example.com',
                'limite_credito' => 1200.00,
            ],
            [
                'nombre' => 'Miguel',
                'apellido' => 'Castillo',
                'identificacion' => '0102030409',
                'telefono' => '0987654329',
                'email' => 'miguel.castillo@example.com',
                'limite_credito' => 650.00,
            ],
            [
                'nombre' => 'Laura',
                'apellido' => 'Ortega',
                'identificacion' => '0102030410',
                'telefono' => '0987654330',
                'email' => 'laura.ortega@example.com',
                'limite_credito' => 850.00,
            ],

            [
                'nombre' => 'Andrés',
                'apellido' => 'Morales',
                'identificacion' => '0102030411',
                'telefono' => '0987654331',
                'email' => 'andres.morales@example.com',
                'limite_credito' => 700.00,
            ],
            [
                'nombre' => 'Gabriela',
                'apellido' => 'Jiménez',
                'identificacion' => '0102030412',
                'telefono' => '0987654332',
                'email' => 'gabriela.jimenez@example.com',
                'limite_credito' => 1100.00,
            ],
            [
                'nombre' => 'Fernando',
                'apellido' => 'Cedeño',
                'identificacion' => '0102030413',
                'telefono' => '0987654333',
                'email' => 'fernando.cedeno@example.com',
                'limite_credito' => 550.00,
            ],
            [
                'nombre' => 'Camila',
                'apellido' => 'Salazar',
                'identificacion' => '0102030414',
                'telefono' => '0987654334',
                'email' => 'camila.salazar@example.com',
                'limite_credito' => 950.00,
            ],
            [
                'nombre' => 'Diego',
                'apellido' => 'Guerrero',
                'identificacion' => '0102030415',
                'telefono' => '0987654335',
                'email' => 'diego.guerrero@example.com',
                'limite_credito' => 400.00,
            ],
            [
                'nombre' => 'Valentina',
                'apellido' => 'Flores',
                'identificacion' => '0102030416',
                'telefono' => '0987654336',
                'email' => 'valentina.flores@example.com',
                'limite_credito' => 1300.00,
            ],
            [
                'nombre' => 'Jorge',
                'apellido' => 'Herrera',
                'identificacion' => '0102030417',
                'telefono' => '0987654337',
                'email' => 'jorge.herrera@example.com',
                'limite_credito' => 500.00,
            ],
            [
                'nombre' => 'Paola',
                'apellido' => 'Navarro',
                'identificacion' => '0102030418',
                'telefono' => '0987654338',
                'email' => 'paola.navarro@example.com',
                'limite_credito' => 700.00,
            ],
            [
                'nombre' => 'Ricardo',
                'apellido' => 'Molina',
                'identificacion' => '0102030419',
                'telefono' => '0987654339',
                'email' => 'ricardo.molina@example.com',
                'limite_credito' => 900.00,
            ],
            [
                'nombre' => 'Natalia',
                'apellido' => 'Paredes',
                'identificacion' => '0102030420',
                'telefono' => '0987654340',
                'email' => 'natalia.paredes@example.com',
                'limite_credito' => 600.00,
            ],

            [
                'nombre' => 'Sebastián',
                'apellido' => 'Vega',
                'identificacion' => '0102030421',
                'telefono' => '0987654341',
                'email' => 'sebastian.vega@example.com',
                'limite_credito' => 1000.00,
            ],
            [
                'nombre' => 'Carolina',
                'apellido' => 'Bravo',
                'identificacion' => '0102030422',
                'telefono' => '0987654342',
                'email' => 'carolina.bravo@example.com',
                'limite_credito' => 750.00,
            ],
            [
                'nombre' => 'José',
                'apellido' => 'Acosta',
                'identificacion' => '0102030423',
                'telefono' => '0987654343',
                'email' => 'jose.acosta@example.com',
                'limite_credito' => 500.00,
            ],
            [
                'nombre' => 'Elena',
                'apellido' => 'Rojas',
                'identificacion' => '0102030424',
                'telefono' => '0987654344',
                'email' => 'elena.rojas@example.com',
                'limite_credito' => 850.00,
            ],
            [
                'nombre' => 'Mauricio',
                'apellido' => 'León',
                'identificacion' => '0102030425',
                'telefono' => '0987654345',
                'email' => 'mauricio.leon@example.com',
                'limite_credito' => 1200.00,
            ],
            [
                'nombre' => 'Verónica',
                'apellido' => 'Sánchez',
                'identificacion' => '0102030426',
                'telefono' => '0987654346',
                'email' => 'veronica.sanchez@example.com',
                'limite_credito' => 650.00,
            ],
            [
                'nombre' => 'Roberto',
                'apellido' => 'Peña',
                'identificacion' => '0102030427',
                'telefono' => '0987654347',
                'email' => 'roberto.pena@example.com',
                'limite_credito' => 950.00,
            ],
            [
                'nombre' => 'Mónica',
                'apellido' => 'Zambrano',
                'identificacion' => '0102030428',
                'telefono' => '0987654348',
                'email' => 'monica.zambrano@example.com',
                'limite_credito' => 700.00,
            ],
            [
                'nombre' => 'Esteban',
                'apellido' => 'Reyes',
                'identificacion' => '0102030429',
                'telefono' => '0987654349',
                'email' => 'esteban.reyes@example.com',
                'limite_credito' => 800.00,
            ],
            [
                'nombre' => 'Patricia',
                'apellido' => 'Muñoz',
                'identificacion' => '0102030430',
                'telefono' => '0987654350',
                'email' => 'patricia.munoz@example.com',
                'limite_credito' => 550.00,
            ],

            [
                'nombre' => 'Cristian',
                'apellido' => 'Espinoza',
                'identificacion' => '0102030431',
                'telefono' => '0987654351',
                'email' => 'cristian.espinoza@example.com',
                'limite_credito' => 1000.00,
            ],
            [
                'nombre' => 'Diana',
                'apellido' => 'Mora',
                'identificacion' => '0102030432',
                'telefono' => '0987654352',
                'email' => 'diana.mora@example.com',
                'limite_credito' => 650.00,
            ],
            [
                'nombre' => 'Alex',
                'apellido' => 'Ponce',
                'identificacion' => '0102030433',
                'telefono' => '0987654353',
                'email' => 'alex.ponce@example.com',
                'limite_credito' => 900.00,
            ],
            [
                'nombre' => 'Rosa',
                'apellido' => 'Chávez',
                'identificacion' => '0102030434',
                'telefono' => '0987654354',
                'email' => 'rosa.chavez@example.com',
                'limite_credito' => 450.00,
            ],
            [
                'nombre' => 'Marco',
                'apellido' => 'Villacís',
                'identificacion' => '0102030435',
                'telefono' => '0987654355',
                'email' => 'marco.villacis@example.com',
                'limite_credito' => 1100.00,
            ],
            [
                'nombre' => 'Andrea',
                'apellido' => 'López',
                'identificacion' => '0102030436',
                'telefono' => '0987654356',
                'email' => 'andrea.lopez@example.com',
                'limite_credito' => 800.00,
            ],
            [
                'nombre' => 'Héctor',
                'apellido' => 'Suárez',
                'identificacion' => '0102030437',
                'telefono' => '0987654357',
                'email' => 'hector.suarez@example.com',
                'limite_credito' => 700.00,
            ],
            [
                'nombre' => 'Lucía',
                'apellido' => 'Cárdenas',
                'identificacion' => '0102030438',
                'telefono' => '0987654358',
                'email' => 'lucia.cardenas@example.com',
                'limite_credito' => 950.00,
            ],
            [
                'nombre' => 'Pablo',
                'apellido' => 'Serrano',
                'identificacion' => '0102030439',
                'telefono' => '0987654359',
                'email' => 'pablo.serrano@example.com',
                'limite_credito' => 600.00,
            ],
            [
                'nombre' => 'Isabel',
                'apellido' => 'Maldonado',
                'identificacion' => '0102030440',
                'telefono' => '0987654360',
                'email' => 'isabel.maldonado@example.com',
                'limite_credito' => 850.00,
            ],

            [
                'nombre' => 'Enrique',
                'apellido' => 'Bustos',
                'identificacion' => '0102030441',
                'telefono' => '0987654361',
                'email' => 'enrique.bustos@example.com',
                'limite_credito' => 500.00,
            ],
            [
                'nombre' => 'Alejandra',
                'apellido' => 'Cabrera',
                'identificacion' => '0102030442',
                'telefono' => '0987654362',
                'email' => 'alejandra.cabrera@example.com',
                'limite_credito' => 1200.00,
            ],
            [
                'nombre' => 'Francisco',
                'apellido' => 'Mora',
                'identificacion' => '0102030443',
                'telefono' => '0987654363',
                'email' => 'francisco.mora@example.com',
                'limite_credito' => 750.00,
            ],
            [
                'nombre' => 'Claudia',
                'apellido' => 'Viteri',
                'identificacion' => '0102030444',
                'telefono' => '0987654364',
                'email' => 'claudia.viteri@example.com',
                'limite_credito' => 900.00,
            ],
            [
                'nombre' => 'Gustavo',
                'apellido' => 'Salinas',
                'identificacion' => '0102030445',
                'telefono' => '0987654365',
                'email' => 'gustavo.salinas@example.com',
                'limite_credito' => 650.00,
            ],
            [
                'nombre' => 'Silvia',
                'apellido' => 'Benítez',
                'identificacion' => '0102030446',
                'telefono' => '0987654366',
                'email' => 'silvia.benitez@example.com',
                'limite_credito' => 800.00,
            ],
            [
                'nombre' => 'Oscar',
                'apellido' => 'Cruz',
                'identificacion' => '0102030447',
                'telefono' => '0987654367',
                'email' => 'oscar.cruz@example.com',
                'limite_credito' => 550.00,
            ],
            [
                'nombre' => 'Lorena',
                'apellido' => 'Guamán',
                'identificacion' => '0102030448',
                'telefono' => '0987654368',
                'email' => 'lorena.guaman@example.com',
                'limite_credito' => 1000.00,
            ],
            [
                'nombre' => 'Manuel',
                'apellido' => 'Pazmiño',
                'identificacion' => '0102030449',
                'telefono' => '0987654369',
                'email' => 'manuel.pazmino@example.com',
                'limite_credito' => 700.00,
            ],
            [
                'nombre' => 'Teresa',
                'apellido' => 'Valencia',
                'identificacion' => '0102030450',
                'telefono' => '0987654370',
                'email' => 'teresa.valencia@example.com',
                'limite_credito' => 900.00,
            ],
        ];

        foreach ($clientes as $cliente) {
            Cliente::create($cliente);
        }
    }
}
